package com.s2m.ss.api.pr.service;

import javax.validation.Valid;

import org.springframework.web.bind.annotation.RequestBody;

import com.s2m.ss.api.pr.entities.SSEnt_OperationType;
import com.s2m.ss.api.pr.entities.SSEnt_TransferType;
import com.s2m.ss.api.pr.entities.SSEnt_ValidateCardPin;
import com.s2m.ss.api.pr.entities.requests.SSEnt_AccountListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_AddSecCardRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_AnonymPrepaidCardRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_AtmMonitoringRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_AuthorizationListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_BaseRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ChannelChangeRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_CheckbookRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_CitiesListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_CreateCardRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_CustomerListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_DebitAppRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_DebitApplicationListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_DebitApplicationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_DebitApplicationValidationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_GetRepositoryRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_HeadInitBnkRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_HeadInitClsRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_HeadInitCrdAccRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_HeadInitCrdRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_InternetMailOrderStatusRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_LimitChangeRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_LinkAccountCardRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ManageAddressRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ManualTransactionRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantAppliListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantAppliValidationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantApplicationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantApplicationUpdateRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantCommissionRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantTerminalTransactionsRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantTransactionsRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MerchantUpdateNoApplicationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_MoneySendRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_OperationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PosApplicationListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PosMonitoringRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PosTerminalApplicationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PosTerminalListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PrepaidAppliValidationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PrepaidApplicationListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_PrepaidApplicationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ProgramRiskRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_RedemptionRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_RenewRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ReplaceCardRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ReplacementRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ResetPinRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_RestCountryChangeRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SelectInterfaceListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SelectTerminalListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SendPinByEmailRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SendPinBySmsRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SetCreditLimitRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SetCustomerInfoRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_SmsAlertRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_StatusMerchantRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_TerminalsByMerchantRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_TransactionsListRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_TransfertRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_UpdateAccountRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_UpdateMobileRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_ValidateCardPinRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_VirtualCardCreationRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_VoidCardlessRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_cardlistRq;
import com.s2m.ss.api.pr.entities.requests.SSEnt_changestatusRq;
import com.s2m.ss.api.pr.entities.responses.SSEnt_AccountsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_AuthorisationRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_BalanceRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_BanksListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_BaseRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_CardInfoRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_CardsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_ChannelsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_ChecksListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_CitiesListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_CountriesListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_CustomerInfoRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_FeesListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_InterfacesListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_LimitsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_LocationsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_MiniStateListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_ProductsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_ReasonsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_RestCountryListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_StatisticsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_TerminalsListRs;
import com.s2m.ss.api.pr.entities.responses.SSEnt_TransactionsListRs;

public interface SSSrv_ApiMobileBanking {

	public SSEnt_CardsListRs getCardsList(SSEnt_HeadInitClsRq headInitReq);
	public SSEnt_TransactionsListRs getTransactionsList(SSEnt_TransactionsListRq transactionsListReq);
	public SSEnt_LimitsListRs getLimitsList(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_ChannelsListRs getChannelsList(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs setStatus(SSEnt_OperationRq operationRq, SSEnt_OperationType changeType);
	public SSEnt_BaseRs setLimits(SSEnt_LimitChangeRq limitChangeReq);
	public SSEnt_BaseRs setRequestPin(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs setChannels(SSEnt_ChannelChangeRq channelChangeReq);
	public SSEnt_BaseRs setReplaceCard(SSEnt_ReplaceCardRq replaceCardReq);
	public SSEnt_BaseRs setAddSecCard(SSEnt_AddSecCardRq addSecCardReq);
	public SSEnt_BalanceRs getBalance(SSEnt_HeadInitCrdAccRq headInitReq);
	public SSEnt_BaseRs setCreateCard(SSEnt_CreateCardRq createCardReq);
	public SSEnt_ProductsListRs getProductsList(SSEnt_HeadInitBnkRq headInitReq);
	public SSEnt_ReasonsListRs getReasonsList(SSEnt_HeadInitBnkRq headInitReq);
	public SSEnt_RestCountryListRs getRestrictedCountry(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs setRestrictedcountry(SSEnt_RestCountryChangeRq restCountryChangeReq);
	public SSEnt_CountriesListRs getCountriesList(SSEnt_HeadInitBnkRq headInitReq);
	public SSEnt_LocationsListRs getLocationsList(SSEnt_HeadInitBnkRq headInitReq);
	public SSEnt_BanksListRs getBanksList(SSEnt_BaseRq baseRq);
	public SSEnt_ChecksListRs getChecksList(SSEnt_HeadInitBnkRq headInitReq);
	public SSEnt_BaseRs pingApi(SSEnt_BaseRq baseReq);
	public SSEnt_AccountsListRs getAccountslist(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs setCheckbook(SSEnt_CheckbookRq checkbookReq);
	public SSEnt_MiniStateListRs getMiniState(SSEnt_HeadInitCrdAccRq headInitReq);
	public SSEnt_StatisticsListRs getStatisticsList(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs setRenewCard(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_AuthorisationRs reqTransfert(SSEnt_TransfertRq billPaymentReq, SSEnt_TransferType requestType);
	public SSEnt_BaseRs setCustomerInfo(SSEnt_SetCustomerInfoRq enrollmentReq);
	public SSEnt_CardInfoRs getCardInfo(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_CustomerInfoRs getCustomerInfo(SSEnt_HeadInitClsRq headInitReq);
	public SSEnt_BaseRs setReqNewCard(SSEnt_DebitAppRq debitAppRq);
	public SSEnt_AccountsListRs getCheckAccountslist(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_AuthorisationRs reqMoneySend(SSEnt_MoneySendRq ent_MoneySendRq);
	public SSEnt_CitiesListRs getCitiesList(@RequestBody  SSEnt_CitiesListRq ent_CitiesListRq);
	public SSEnt_TerminalsListRs getTerminalList(@Valid SSEnt_SelectTerminalListRq selectListRq);
	public SSEnt_InterfacesListRs getInterfaceList(@Valid SSEnt_SelectInterfaceListRq interfaceListRq);
	public SSEnt_FeesListRs getFeesList(SSEnt_HeadInitCrdRq headInitReq);
	public SSEnt_BaseRs linkAccountToCard(SSEnt_LinkAccountCardRq linkAccountCardRq);
	public SSEnt_AuthorisationRs reqManualTrx(SSEnt_ManualTransactionRq manualTransactionRq);
	public SSEnt_AuthorisationRs setCreditLimit(SSEnt_SetCreditLimitRq creditLimitRq);
	public SSEnt_BaseRs reqVoidCardless(SSEnt_VoidCardlessRq voidCardlessRq);
	public String getRepository(SSEnt_GetRepositoryRq repoRq);
	public String changestatus(SSEnt_changestatusRq changesttsRq);
	public String validateCardPin(SSEnt_ValidateCardPinRq validateCardPinRq);
	public String PrepaidApplication(SSEnt_PrepaidApplicationRq prepaidApplicationRq);
	public String PrepaidApplicationValidation(SSEnt_PrepaidAppliValidationRq prepaidApplicationvaliRq);
	public String PrepaidApplicationList(SSEnt_PrepaidApplicationListRq prepaidApplicationlistRq);
	public String Redemption(SSEnt_RedemptionRq RedemptionRq) ;
	public String PosMonitoring(SSEnt_PosMonitoringRq posMonitoringRq) ;
	public String MerchantApp(SSEnt_MerchantApplicationRq merchantappliRq);
	public String MerchantAppVali(SSEnt_MerchantAppliValidationRq merchantapplivaliRq);
	public String MerchantAppUpdate(SSEnt_MerchantApplicationUpdateRq merchantappliUpdate);
	public String MerchantAppliList(SSEnt_MerchantAppliListRq merchantApplist);
	public String PosTerminalList(SSEnt_PosTerminalListRq posterminallist);
	public String MerchantUpdateNoApplication(SSEnt_MerchantUpdateNoApplicationRq merchantupdatenoApp) ;
	public String PosTerminalapplication(SSEnt_PosTerminalApplicationRq posterminalapp); 
	public String AuthorizationList(SSEnt_AuthorizationListRq authList);
	public String PosApplicationList(SSEnt_PosApplicationListRq posappList);
	public String UpdateMobile(SSEnt_UpdateMobileRq updatemobile);
	public String UpdateAccount(SSEnt_UpdateAccountRq updateaccount);
	public String UpdateMerchantStatus(SSEnt_StatusMerchantRq statusmerchant);
	public String InternetMailOrderStatus(SSEnt_InternetMailOrderStatusRq internetmailorder);
	public String AnonymPrepaidCard(SSEnt_AnonymPrepaidCardRq anonymprepaid);
	public String MerchantCommission(SSEnt_MerchantCommissionRq merchantcommi);
	public String ManageAddress(SSEnt_ManageAddressRq manageadress);
	public String TerminalsByMerchant(SSEnt_TerminalsByMerchantRq terminalsbymerchant);
	public String GetMerchantTransactions(SSEnt_MerchantTransactionsRq merchantransac);
	public String MerchantTerminalTransactions(SSEnt_MerchantTerminalTransactionsRq merchantterminaltransac);
	public String SendPinBySms(SSEnt_SendPinBySmsRq sendpinbysms);
	public String ProgramRisk(SSEnt_ProgramRiskRq programrisk);
	public String SmsAlert(SSEnt_SmsAlertRq smsalert);
	public String SendPinByEmail(SSEnt_SendPinByEmailRq pinemail);
	public String AtmMonitoring(SSEnt_AtmMonitoringRq atmmonitoring);
	public String VirtualCardCreation(SSEnt_VirtualCardCreationRq virtualcard);
	public String DebitApplication(SSEnt_DebitApplicationRq debitappli);
	public String DebitApplicationValidation(SSEnt_DebitApplicationValidationRq debitapplivali);
	public String DebitApplicationList(SSEnt_DebitApplicationListRq debitapplilist);
	public String ResetPin(SSEnt_ResetPinRq resetpin);
	public String Replacement(SSEnt_ReplacementRq replacement);
	public String Renew(SSEnt_RenewRq Renew);
	public String CardList(SSEnt_cardlistRq Cardlist);
	public String AccountList(SSEnt_AccountListRq accountlist);
	public String CustomerList(SSEnt_CustomerListRq customerlist);
}
